# Generated by Django 5.1 on 2024-08-14 13:29

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Luminary_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField(default='')),
                ('blockquote', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio')),
                ('image', models.ImageField(upload_to='essay-images')),
                ('luminary_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Luminary_registration.luminarywriter')),
                ('essay_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Luminary_essays.essaycategory')),
            ],
        ),
    ]
