# Generated by Django 5.1 on 2024-08-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminary_essays', '0001_initial'),
        ('Luminary_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='luminary_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Luminary_registration.luminarywriter'),
        ),
    ]
