# Generated by Django 5.1 on 2024-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luminary_essays', '0002_alter_essay_luminary_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='blockquote',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
