# Generated by Django 5.1 on 2024-08-13 14:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Luminary_essays', '0003_essay_blockquote_alter_essay_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
